#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 28
#SBATCH --time 00:01:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC024002
#SBATCH --account=COSC024002
#SBATCH --output d2q9-bgk.out
#SBATCH --exclude=compute086,compute087

# export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
# srun ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# srun ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# srun ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# srun ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

# mpiexec -n 112 amplxe-cl -quiet -collect hotspots -result-dir output ./d2q9-bgk input_128x128.params obstacles_128x128.dat

# mpiexec -n 112 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# mpiexec -n 112 ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# mpiexec -n 112 ./d2q9-bgk input_256x256.params obstacles_256x256.dat
mpiexec -n 112 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

# srun amplxe-cl –c hotspots –r otrput ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# srun amplxe-cl –c hotspots –r otrput ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# srun amplxe-cl –c hotspots –r otrput ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# srun amplxe-cl –c hotspots –r otrput ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat